### ISSUE TITLE
Не работает coverage

### ISSUE THREAD

**Issue by OneSeven17** [OneSeven17/HW3lessonV2#1]
Нет 100% покрытия. 

<img width="648" alt="2019-02-17 20 11 11" src="https://user-images.githubusercontent.com/47249843/52916419-3c7ee600-32f0-11e9-9035-ebdc33d16c8e.png">

<img width="1243" alt="2019-02-17 20 05 03" src="https://user-images.githubusercontent.com/47249843/52916349-6683d880-32ef-11e9-8b3f-0f0031c9a48b.png">

**Comment by coursar** [comment]
Создайте в каталоге app пустой файлик _​​_​​init_​​_​​.py
